### ISSUE TITLE
PDM init  -  [AttributeError]: 'LegacyVersion' object has no attribute 'major'

### ISSUE THREAD

**Issue by yeaTry** [pdm-project/pdm#1018]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

```python
Creating a pyproject.toml for PDM...
Please enter the Python interpreter to use
0. C:\Program Files\Python310\python.EXE (3.10)
1. C:\Program Files\Python38\python.exe (3.8)
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\users\xxx\appdata\roaming\python\scripts\pdm.exe\__main__.py", line 7, in <module>
  File "C:\Users\xxx\AppData\Roaming\pdm\venv\lib\site-packages\pdm\core.py", line 233, in main
    return Core().main(args)
  File "C:\Users\xxx\AppData\Roaming\pdm\venv\lib\site-packages\pdm\core.py", line 168, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "C:\Users\xxx\AppData\Roaming\pdm\venv\lib\site-packages\pdm\core.py", line 163, in main
    f(options.project, options)
  File "C:\Users\xxx\AppData\Roaming\pdm\venv\lib\site-packages\pdm\cli\commands\init.py", line 46, in handle
    actions.do_use(project)
  File "C:\Users\xxx\AppData\Roaming\pdm\venv\lib\site-packages\pdm\cli\actions.py", line 579, in do_use
    f"({py_version.identifier})"
  File "C:\Users\xxx\AppData\Roaming\pdm\venv\lib\site-packages\pdm\models\python.py", line 76, in identifier
    return f"{self.major}.{self.minor}"
  File "C:\Users\xxx\AppData\Roaming\pdm\venv\lib\site-packages\pdm\models\python.py", line 51, in major
    return self._py_ver.major
  File "C:\Users\xxx\AppData\Roaming\pdm\venv\lib\site-packages\findpython\python.py", line 68, in major
    return self.version.major
AttributeError: 'LegacyVersion' object has no attribute 'major'
```

## Steps to reproduce
pdm init -v

## Actual behavior

Show error message and break.

## Expected behavior

Just like my another 2 projects, created corresponding files and dir.

## Environment Information
```bash
# Paste the output of `pdm info && pdm info --env` below:
[ProjectError]: The pyproject.toml has not been initialized yet. You can do this by running 'pdm init'.
```

**Comment by yeaTry** [comment]
Under the same project directory, Poetry is ok.

**Comment by frostming** [comment]
Can you show what Python interpreters are found?

```
C:\Users\xxx\AppData\Roaming\pdm\venv\Scripts\findpython.exe -a
```

> Just like my another 2 projects, created corresponding files and dir.

So those projects are good? What is the difference? Please provide as much information as you can rather than a simple `pdm init` fails

**Comment by YorigamiShion** [comment]
I met the same problem from `pdm init -v`.
Running `~\scoop\apps\pdm\1.14.0\venv\Scripts\findpython.exe -a`, output is below.

```
Found matching python versions:
python.exe 3.10.4 @ C:\Users\xxx\scoop\apps\python\current\python.exe
python3.exe 3.10.4 @ C:\Users\xxx\scoop\shims\python3.exe
python.exe py39_4.10.3 @ C:\Users\xxx\MiniConda3\python.exe
```

**Comment by frostming** [comment]
This is resolved in the new release of `findpython`. You will need to find a way to upgrade this dependency used by PDM.

**Comment by johnbendi** [comment]
I still get get this error when trying to specify a python binary with pdm installation having `findpython 0.2.1`

**Comment by frostming** [comment]
> I still get get this error when trying to specify a python binary with pdm installation having `findpython 0.2.1` on a Linux platform

Is there any prerelease python version installed
