### ISSUE TITLE
[Windows] NoPythonVersion: Python interpreter is not found on the system.

### ISSUE THREAD

**Issue by cye18** [pdm-project/pdm#980]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

I'm using Windows machine. I installed PDM with pip in Python3.7 version. I run `pdm sync` and it returns

```
Traceback (most recent call last):
  File "c:\users\cye1\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\cye1\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\Scripts\pdm.exe\__main__.py", line 7, in <module>
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\site-packages\pdm\core.py", line 233, in main
    return Core().main(args)
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\site-packages\pdm\core.py", line 168, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\site-packages\pdm\core.py", line 163, in main
    f(options.project, options)
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\site-packages\pdm\cli\commands\run.py", line 280, in handle
    sys.exit(runner.run(options.command, options.args))
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\site-packages\pdm\cli\commands\run.py", line 220, in run
    [command] + args, **self.global_options  # type: ignore
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\site-packages\pdm\cli\commands\run.py", line 98, in _run_process
    project_env = project.environment
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\site-packages\pdm\project\core.py", line 224, in environment
    self._environment = self.get_environment()
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\site-packages\pdm\project\core.py", line 219, in get_environment
    return Environment(self)
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\site-packages\pdm\models\environment.py", line 75, in __init__
    self.interpreter: PythonInfo = project.python
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\site-packages\pdm\project\core.py", line 157, in python
    self._python = self.resolve_interpreter()
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\site-packages\pdm\project\core.py", line 195, in resolve_interpreter
    for py_version in self.find_interpreters():
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\site-packages\pdm\project\core.py", line 610, in find_interpreters
    for entry in finder.find_all(*args):
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\site-packages\findpython\finder.py", line 94, in find_all
    matched_python = set(self._find_all_python_versions())
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\site-packages\findpython\finder.py", line 127, in _find_all_python_versions
    yield from provider.find_pythons()
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\site-packages\findpython\providers\path.py", line 25, in find_pythons
    yield from self.find_pythons_from_path(path)
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\site-packages\findpython\providers\base.py", line 50, in <genexpr>
    if path_is_python(child)
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\site-packages\findpython\utils.py", line 93, in path_is_python
    if not path_is_readable(path) or not path.is_file():
  File "c:\users\cye1\anaconda3\lib\pathlib.py", line 1382, in is_file
    return S_ISREG(self.stat().st_mode)
  File "c:\users\cye1\anaconda3\lib\pathlib.py", line 1178, in stat
    return self._accessor.stat(self)
OSError: [WinError 1920] The file cannot be accessed by the system: 'C:\\Users\\cye1\\AppData\\Local\\Microsoft\\WindowsApps\\MicrosoftEdge.exe'
```

I have no idea why MicrosoftEdge is involved in this scenario. :joy:

I figured it could be due to my messy Python environment, so I installed Python3.9 and tried to use `pdm use -v C:/Users/cye1/AppData/Local/Programs/Python/Python39/python` to let PDM use the new Python3.9. It shows (see Actual behavior)

## Actual behavior

```
Traceback (most recent call last):
  File "c:\users\cye1\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\cye1\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\Scripts\pdm.exe\__main__.py", line 7, in <module>
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\site-packages\pdm\core.py", line 233, in main
    return Core().main(args)
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\site-packages\pdm\core.py", line 168, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\site-packages\pdm\core.py", line 163, in main
    f(options.project, options)
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\site-packages\pdm\cli\commands\use.py", line 30, in handle
    project, options.python, options.first, options.ignore_remembered
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\site-packages\pdm\cli\actions.py", line 563, in do_use
    raise NoPythonVersion("Python interpreter is not found on the system.")
pdm.exceptions.NoPythonVersion: Python interpreter is not found on the system.
```

## Expected behavior

PDM to recognize the Python3.9 interpreter and use it smoothly.

## Environment Information

It shows the OSError again when I run `pdm info && pdm info --env`

```bash
# Paste the output of `pdm info && pdm info --env` below:
$ pdm info && pdm info --env
[OSError]: [WinError 1920] The file cannot be accessed by the system: 'C:\\Users\\cye1\\AppData\\Local\\Microsoft\\WindowsApps\\MicrosoftEdge.exe'
Add '-v' to see the detailed traceback
```

Maybe my PDM is not installed properly? Thanks for your help! :smiling_face_with_three_hearts:

**Comment by frostming** [comment]
Shouldn't it be `C:/Users/cye1/AppData/Local/Programs/Python/Python39/python.exe` ?

**Comment by cye18** [comment]
I believe I've tried `python.exe` before I ended up with `python` and it didn't work then. But it does work now. :joy:

My bad. I'm now able to proceed with my project. Thanks a lot!

**Comment by cye18** [comment]
I see the issue again. Since it's pretty much the same issue, I'd reopen this issue rather than create a new one.

## Steps to reproduce

Create a new folder right next to the previous one. Run `pdm init` and got the same `OSError` again.

This time I used the correct `pdm use -v C:/Users/cye1/AppData/Local/Programs/Python/Python39/python.exe` command. It seems to be all set by showing

```
Using the last selection, add '-i' to ignore it.
Using Python interpreter: C:\Users\cye1\AppData\Local\Programs\Python\Python39\python.exe (3.9)
```

However, when I run `pdm init`, it still shows the `OSError`.

For your convenience, the error message is pasted here.

```
$ pdm init -v
Creating a pyproject.toml for PDM...
Traceback (most recent call last):
  File "c:\users\cye1\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\cye1\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\Scripts\pdm.exe\__main__.py", line 7, in <module>
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\site-packages\pdm\core.py", line 233, in main
    return Core().main(args)
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\site-packages\pdm\core.py", line 168, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\site-packages\pdm\core.py", line 163, in main
    f(options.project, options)
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\site-packages\pdm\cli\commands\init.py", line 46, in handle
    actions.do_use(project)
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\site-packages\pdm\cli\actions.py", line 560, in do_use
    found_interpreters = list(dict.fromkeys(project.find_interpreters(python)))
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\site-packages\pdm\project\core.py", line 610, in find_interpreters
    for entry in finder.find_all(*args):
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\site-packages\findpython\finder.py", line 94, in find_all
    matched_python = set(self._find_all_python_versions())
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\site-packages\findpython\finder.py", line 127, in _find_all_python_versions
    yield from provider.find_pythons()
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\site-packages\findpython\providers\path.py", line 25, in find_pythons
    yield from self.find_pythons_from_path(path)
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\site-packages\findpython\providers\base.py", line 50, in <genexpr>
    if path_is_python(child)
  File "C:\Users\cye1\AppData\Roaming\Python\Python37\site-packages\findpython\utils.py", line 93, in path_is_python
    if not path_is_readable(path) or not path.is_file():
  File "c:\users\cye1\anaconda3\lib\pathlib.py", line 1382, in is_file
    return S_ISREG(self.stat().st_mode)
  File "c:\users\cye1\anaconda3\lib\pathlib.py", line 1178, in stat
    return self._accessor.stat(self)
OSError: [WinError 1920] The file cannot be accessed by the system: 'C:\\Users\\cye1\\AppData\\Local\\Microsoft\\WindowsApps\\MicrosoftEdge.exe'
```

## What I tried

I tried to copy the `pyproject.toml` and `pdm.lock` from the previous folder to the new one and run `pdm sync`. It works and I'm able to run all `pdm` commands, so I'm able to get the environment info below. It looks like PDM has problem creating `pyproject.toml` by `pdm init`. Once it's created, everything works well.

## Environment Information

```
$ pdm info && pdm info --env
PDM version:        1.13.4
Python Interpreter: C:\Users\cye1\AppData\Local\Programs\Python\Python39\python.exe (3.9)
Project Root:       C:/Users/cye1/work/project_name
Project Packages:   C:\Users\cye1\work\project_name\__pypackages__\3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.11",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.18363",
  "python_full_version": "3.9.11",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "win32"
}
```

## Expected behavior

- Sicne I've successfully configured the python interpreter in the previous folder, it shouldn't have the same issue with a new folder. At least when I set up Python interpreter with `pdm use`, it should use the specified interpreter, rather than use Python3.7 and end up looking for `MicrosoftEdge.exe`
- Just curious why `MicrosoftEdge.exe` is involved here?

Thank you very much!

**Comment by frostming** [comment]
Something bad happens when PDM searches the `PATH` to find a python executable. `'C:\\Users\\cye1\\AppData\\Local\\Microsoft\\WindowsApps\\MicrosoftEdge.exe'` raises error when checked against `Path.is_file()`.

**Comment by frostming** [comment]
This issue should be fixed in the new release of `findpython`, and those executables will be skipped.

**Comment by cye18** [comment]
I see it was just released. Thanks! Do I need to reinstall or update PDM?

**Comment by cye18** [comment]
For anyone who has the issue as well, I uninstalled and reinstalled PDM using `pip install pdm`. `findpython==0.1.3` was installed by default, so the error still happened. I ran `pip install update findpython==0.1.4` and it's fixed.
